In [1]:
import numpy as np

In [8]:
arr = np.arange(10)

In [9]:
np.save('some_array', arr)

In [10]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('array_archive.npz', a=arr, b=arr)

In [12]:
arch = np.load('array_archive.npz')

In [13]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [16]:
from numpy.linalg import inv, qr

In [17]:
X = np.random.randn(5, 5)

In [18]:
mat = X.T.dot(X)

In [19]:
inv(mat)

array([[ 2.85899391, -0.43250063,  2.72038724,  2.74426132, -0.63873274],
       [-0.43250063,  0.33056489, -0.02788592, -0.05273374,  0.0734669 ],
       [ 2.72038724, -0.02788592,  4.54169708,  3.96426045, -0.76300066],
       [ 2.74426132, -0.05273374,  3.96426045,  3.84328683, -0.71067816],
       [-0.63873274,  0.0734669 , -0.76300066, -0.71067816,  0.43220349]])

In [20]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  7.47304281e-17, -5.22395197e-16,
         3.41036303e-15,  1.00293489e-16],
       [-6.61359454e-16,  1.00000000e+00, -2.03877766e-15,
         8.65207707e-16,  2.82831824e-16],
       [-6.13490812e-16,  2.22197136e-17,  1.00000000e+00,
         1.29962672e-16,  7.15203784e-17],
       [-1.27141904e-16, -8.28449660e-17,  1.31285716e-15,
         1.00000000e+00,  2.12899597e-16],
       [-2.44080221e-16, -5.84187342e-17, -3.61924093e-16,
         4.31935956e-16,  1.00000000e+00]])

In [21]:
q, r = qr(mat)

In [23]:
r

array([[-4.411792  , -6.90465339, -2.0653221 ,  5.16893577, -0.77341456],
       [ 0.        , -2.68358757,  1.5256076 , -1.41345537,  1.62272235],
       [ 0.        ,  0.        , -2.54033355,  2.82772075,  0.53078418],
       [ 0.        ,  0.        ,  0.        , -0.66153228, -3.06573493],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.76982084]])